default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  url: <%= ENV['DATABASE_URL_VOTES'] %> 

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_VOTES'] %> 

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL_VOTES'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_VOTES'] %> 
